using Extension.Extractor;
using System;
using System.Collections.Generic;
using System.Data;

namespace Aibe.Models.DB {
  [Serializable]
  public class BaseMetaItem : IMetaItem { //To be used for base operation, and to create the crypto-files
    public int Cid { get; set; }
    public string TableName { get; set; }
    public string DisplayName { get; set; }
    public string TableSource { get; set; }
    public string PrefilledColumns { get; set; }
    public short? ItemsPerPage { get; set; }
    public string OrderBy { get; set; }
    public string ActionList { get; set; }
    public string DefaultActionList { get; set; }
    public string TableActionList { get; set; }
    public string DefaultTableActionList { get; set; }
    public string TextFieldColumns { get; set; }
    public string PictureColumns { get; set; }
    public string IndexShownPictureColumns { get; set; }
    public string RequiredColumns { get; set; }
    public string NumberLimitColumns { get; set; }
    public string RegexCheckedColumns { get; set; }
    public string RegexCheckedColumnExamples { get; set; }
    public string UserRelatedFilters { get; set; }
    public bool? DisableFilter { get; set; }
    public string ForcedFilterColumns { get; set; }
    public string ColumnExclusionList { get; set; }
    public string FilterExclusionList { get; set; }
    public string DetailsExclusionList { get; set; }
    public string CreateEditExclusionList { get; set; }
    public string CsvExclusionList { get; set; }
    public string AccessExclusionList { get; set; }
    public string ColoringList { get; set; }
    public string FilterDropDownLists { get; set; }
    public string CreateEditDropDownLists { get; set; }
    public string PrefixesOfColumns { get; set; }
    public string PostfixesOfColumns { get; set; }
    public string ListColumns { get; set; }
    public string TimeStampColumns { get; set; }
    public string HistoryTable { get; set; }
    public string HistoryTriggers { get; set; }
    public string AutoGeneratedColumns { get; set; }
    public string ColumnSequence { get; set; }
    public string ColumnAliases { get; set; }
    public string EditShowOnlyColumns { get; set; }
    public string ScriptConstructorColumns { get; set; }
    public string ScriptColumns { get; set; }
    public string CustomDateTimeFormatColumns { get; set; }
    public string EmailMakerTriggers { get; set; }
    public string EmailMakers { get; set; }
    public string NonPictureAttachmentColumns { get; set; }
    public string DownloadColumns { get; set; }
    public string PreActionTriggers { get; set; }
    public string PreActionProcedures { get; set; }
    public string PostActionTriggers { get; set; }
    public string PostActionProcedures { get; set; }
    public string TableType { get; set; }
    public string AggregationStatement { get; set; }
    public string ForeignInfoColumns { get; set; }

    public static BaseMetaItem ExtractMetaFromDataTable(DataTable table) {
      return BaseExtractor.Extract<BaseMetaItem>(table);
    }

    public static List<BaseMetaItem> ExtractMetasFromDataTable(DataTable table) {
      return BaseExtractor.ExtractList<BaseMetaItem>(table);
    }

    public string BuildSqlInsertString() {
      return BaseExtractor.BuildSqlInsertString(DH.MetaTableName, this, new List<string> { DH.Cid }, DH.DefaultDateTimeFormat, PH.DBProviderIsOracle);
    }

    public string BuildSqlUpdateString() {
      return BaseExtractor.BuildSqlUpdateString(DH.MetaTableName, this, DH.Cid, Cid.ToString(), false, new List<string> { DH.Cid }, DH.DefaultDateTimeFormat, PH.DBProviderIsOracle);
    }
  }
}